[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eland领地插件"
version = "7.0.0"
description = "领地"

[project.entry-points."endstone"]
ye111566-land = "endstone_ye111566_land:Ye111566Land"
